# Site
repository: ulbrichdennis/ulbrichdennis.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Dr. Dennis Ulbrich
title: Postdoctoral researcher
email: 
# email_title:  
#phone: 
# phone_title: Phone (Phone title override)
website: 
# website_title: Web (Website title override)
contactdata: https://www.dulbrich.de/index.html#Contact
contactdata_title: Contact


# Dark Mode (true/false/never)
darkmode: false


# Social links
#twitter_username: jekyllrb
#github_username:  jekyll
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: 
linkedin_username: ulbrichdennis
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
orcid_username: 0000-0001-5541-011X
googlescholar_username: b1u5plUAAAAJ

# Additional icon links
additional_links:
- title: Link name
  icon: fab fa-researchgate
  url: https://www.researchgate.net/profile/Dennis-Ulbrich-2
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/UD.jpeg 
about_content: | # this will include new lines to allow paragraphs

  Currently, I am a postdoctoral researcher at [Faculty 4](https://www.hs-bremen.de/en/hsb/faculties/school-of-electrical-engineering-and-computer-science/#c1325) of the [Bremen University of Applied Sciences](https://www.hs-bremen.de/en/).

  Beforehand, I was a postdoctoral researcher at the [Institute for Analysis and Numerics](https://www.uni-muenster.de/AMM/en/institute.shtml) at the [University of Münster](https://www.uni-muenster.de/en/).
  
  I earned my PhD degree in Mathematics (*Dr. rer. nat.* in Mathematics) at the [University of Bremen](https://www.uni-bremen.de/en/), cf. [MGP](https://www.mathgenealogy.org/id.php?id=277103). 

  Some more details and further information, including my teaching activities, can be found below.
  
 # <img src="/images/logo.svg" width="200px" height="100px">
 

  

content:
  - title: Research interests # Title for the section
    layout: text
    content: |
     * Ordinary and partial differential equations and their dynamics
     * Dynamical Systems and Ergodic Theory
     * Kinetic Theory and Entropy methods
     * Boltzmann equation and its BGK-type approximations
     * Long-time behavior of solutions (Hypocoercivity)
     * Models of chemical reactions
     * Physical applications
  - title: Projects  
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: DFG 456849348
        link: https://gepris.dfg.de/gepris/projekt/456849348?bundesland=DEU%23&fachgebiet=%23&findButton=historyCall&ggsHunderter=0&hitsPerPage=25&index=128925&language=en&lis=%23&nurProjekteMitAB=false&oldGgsHunderter=0&teilprojekte=true
        link_text: Link to project
        #additional_links:
          #- title:  Github page for project (eg. sproogen/modern-resume-theme)
            #icon: fab fa-github
            #url: https://gepris.dfg.de/gepris/projekt/456849348?bundesland=DEU%23&fachgebiet=%23&findButton=historyCall&ggsHunderter=0&hitsPerPage=25&index=128925&language=en&lis=%23&nurProjekteMitAB=false&oldGgsHunderter=0&teilprojekte=true
          #- title:  Github page for project (eg. sproogen/modern-resume-theme)
           # icon: fab fa-github
           # url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Modeling and mathematical description of concrete physical applications in the context of<br>kinetic theory using the Bathnagar-Gross-Krook equation
        description: | # this will include new lines to allow paragraphs
                     + Term 2021 - 2025
                     + Participation since 6.2023
      - layout: left
        border: weak
        title: DATIPilot - Sprint - Lector4Teachers
        link: https://www.hs-bremen.de/forschen/forschungs-und-transferprofil/forschungsprojekt/datipilot-sprint-lector4teachers-ki-basierte-uebertragung-analyse-und-pruefung-handgeschriebener-dokumente-zur-entlastung-von-lehrerinnen-tp-a/
        link_text: Link to project
        quote: >
          AI-based transfer, analysis and review of handwritten documents to relieve teachers
        description: |
            + Term 12.2024 - 5.2026
            + Participation since 2.2025 
      - layout: left
        #border: weak
        title: DFG 384027439
        link: https://gepris.dfg.de/gepris/projekt/384027439?language=en&selectedSubTab=2
        link_text: Link to project
        quote: >
         Ergodic theory of nonlinear waves in discrete and continuous excitable media
        description: | # this will include new lines to allow paragraphs  
                     + Term 2017 - 2021
                     + Participation 2017 - 2021
  - title: Publications
    layout: text
    content: |
    
      ## In progress
      
        * *Discrete hypocoercivity for a nonlinear generation-recombination model.* <br>
           joint work with [L. Liu](https://www.math.cuhk.edu.hk/~lliu/) and [M. Pirner](https://www.uni-muenster.de/AMM/en/Pirner/index.shtml)
    
      ## Refereed journal articles
    
        * A. Pauthier, J.D.M. Rademacher, D. Ulbrich.<br>
          *Weak and strong interaction of excitation kinks in scalar parabolic equations.*<br>
          J Dyn Diff Equat. Published 30 July 2021; Volume 35, pages 2199-2235, (2023) [[DOI]](https://link.springer.com/article/10.1007/s10884-021-10040-2) [[arXiv]](https://arxiv.org/abs/2012.00309)
        * M. Keßeböhmer, J.D.M. Rademacher, D. Ulbrich.<br>
          *Dynamics and topological entropy of 1D Greenberg-Hastings cellular automata.*<br>
          Ergodic Theory and Dynamical Systems. 2021;41(5):1397-1430 [[DOI]](https://www.cambridge.org/core/journals/ergodic-theory-and-dynamical-systems/article/dynamics-and-topological-entropy-of-1d-greenberghastings-cellular-automata/1DBE1EC4EC7BE9F216E9E35C214F2F3C) [[arXiv]](https://arxiv.org/abs/1903.02459)
        
      ## Theses
      
         * D. Ulbrich.<br>
           *Ergodic theory of nonlinear waves in discrete and continuous excitable media.*<br>
           Dissertation, 2021 [[DOI]](https://media.suub.uni-bremen.de/handle/elib/5257)
          
  - title: Short CV
    layout: list
    content:
      - layout: top-right
        border: weak
        title: Hochschule Bremen
        sub_title: Postdoctoral researcher
        caption: from 2.2025
        quote: >
            Faculty 4: School of Electrical Engineering and Computer Science 
        description: |
          + Conception and development of deep learning approaches to text recognition and extraction
          + Development of a modern application for the usage of the developed deep learning approaches
             + *Supervision:* [Prof. Draheim](https://www.hs-bremen.de/person/pdraheim/)
      - layout: top-right
        border: weak
        title: University of Münster
        sub_title: Postdoctoral researcher
        caption: 6.2023 - 6.2024
        quote: >
           Faculty of Mathematics and Computer Science<br>
           Institute for Analysis and Numerics
        description: | # this will include new lines to allow paragraphs
          + Research on discrete hypocoercivity within DFG project 456849348:
             + *Supervision:* [Prof. Pirner](https://www.uni-muenster.de/AMM/en/Pirner/index.shtml)
          + Keywords:
            + <mark>Hypocoercivity</mark>
            + <mark>Kinetic equations</mark>
            + <mark>BGK-type approximations</mark>
            + <mark>Chemical reactions</mark>
            + <mark>Entropy methods</mark>
      - layout: top-right
        border: weak 
        title: University of Bremen
        sub_title: PhD student and research assistant <br>
                   PhD degree (Dr. rer. nat.) in 8.2021
        caption: 4.2016 - 9.2021
        quote: >
           Department of Mathematics<br>
           Research groups: Nonlinear Analysis and Applied Analysis,<br>
           Stochastics and Dynamical Systems<br>
        description: |
         + Research within DFG project number 384027439
         + PhD thesis: *Ergodic theory of nonlinear waves in discrete and continuous excitable media*:
            + *Advisors:* [Prof. Rademacher](https://www.math.uni-hamburg.de/en/forschung/bereiche/am/ang-dynamische-systeme/personen/rademacher-jens.html), [Prof. Keßeböhmer](https://www.uni-bremen.de/dynsys/members/prof-dr-marc-kesseboehmer)
            + *Referees:* Prof. Rademacher (University of Bremen), [Prof. Melbourne](https://warwick.ac.uk/fac/sci/maths/people/staff/ian_melbourne/) (Warwick University)
         + Keywords:
            + <mark>Nonlinear analysis</mark>
            + <mark>Ergodic Theory</mark>
            + <mark>PDE</mark>
            + <mark>Excitable media</mark> 
            + <mark>Cellular automata</mark>
            + <mark>Dynamical Systems</mark>
      - layout: top-right
        title: University of Bremen
        sub_title: Study of Mathematics<br>
                  Master and Bachelor degree (M.Sc. and B.Sc.)
        caption: until 4.2016
        quote: >
         Department of Mathematics
        description: |
         + M.Sc. thesis: *Dynamics of the three-state 1D Greenberg-Hastings cellular automaton*
            + *Referees:* Prof. Rademacher, [Dr. Samuel](https://tony-samuel.github.io/index.html) (University of Exeter)
         + B.Sc. thesis: *Unerwartete Fehler bei bedingten Erwartungswerten und Wahrscheinlichkeiten*
            + *Referees:* [Prof. Brannath](https://www.uni-bremen.de/kksb/biometrie/team/mitglieder/prof-dr-werner-brannath) (University of Bremen), [Dr. Falk](https://www.math.uni-kiel.de/de/personen/a-z/dr-kurt-falk) (University of Kiel)
  - title: Short CV (Teaching)
    layout: list
    content:
      - layout: right
        border: weak
        title: Hochschule Bremen
        sub_title: Lecturer
        caption: Winter semester 2024/25
        link: 
        quote: >
          Faculty 5: School of Nature and Engineering
        description: | # this will include new lines to allow paragraphs
           + *Mathematik 1* (MATH1)
             + Undergraduate lecture
      - layout: right
        title: Jacobs University Bremen
        sub_title: Lecturer
        caption: Spring term 2022
        quote: > 
          School of Science
        description: |
          + *Finite Mathematics*
             + Undergraduate lecture
          + *Introduction to Dynamical Systems*
             + proseminar
  - title: Other 
    layout: text
    content: | # this will include new lines to allow paragraphs
      ## Grants
        + [Brückenstipendium](https://www.uni-bremen.de/fileadmin/user_upload/forschung/Anlage/Stipendium/Merkblatt_Brueckenstip.pdf), Universität Bremen, 2016 -- 2017

      ## Supervision

         + University of Bremen, 2020 -- 2021<br>
          Student Research Project<br>
          *Wave patterns in cellular automata for excitable media*

      ## Organisation etc.

         + University of Bremen, 2016 -- 2021<br>
           Supporting several [summer and winter schools](https://www.uni-bremen.de/dynamical-systems/past-events/bremen-summer-and-winter-schools-on-dynamical-systems)
         + University of Bremen, 2017 -- 2021<br>
           Maintaining the Mathematical Collection and creating its [website](https://www.uni-bremen.de/appanalysis/mathematical-collection/)   
  - title: <a id="Contact">Contact</a> 
    layout: text
    content: | # this will include new lines to allow paragraphs 
         ## Address

            Hochschule Bremen<br>
            Fakultät 4 <br>
            Flughafenallee 10<br>
            28199 Bremen

         ## [ZIMT, Office: tba](https://www.hs-bremen.de/raumfinder/)

         ## [Phone: tba](tel:+49)

         ## [Email](mailto:dennis.ulbrich@hs-bremen.de)

         

         

           
    
        

      
footer_show_references: true
references_title: Last modified Jan 28, 2025 

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
