---
title: "Research"
subtitle: "Interests and publications"
description-meta: "What I am interested in and what I have published so far"
title-block-banner: true
date-modified: last-modified
date-format: iso
css: bootstrap.css
---

## Research interests

* Ordinary and partial differential equations and their dynamics
* Dynamical Systems and Ergodic Theory
* Kinetic Theory and Entropy methods
* Boltzmann equation and its BGK-type approximations
* Long-time behavior of solutions (Hypocoercivity)
* Models of chemical reactions
* Physical applications

## Publications

### In progress

- *Discrete hypocoercivity for a nonlinear kinetic
reaction model without initial
close-to-equilibrium assumption.* (working title) <br>
  joint work with [L. Liu](https://www.math.cuhk.edu.hk/~lliu/) and [M. Pirner](https://www.uni-muenster.de/AMM/en/Pirner/index.shtml)

### Refereed journal articles

* A. Pauthier, J.D.M. Rademacher, D. Ulbrich.<br>
  *Weak and strong interaction of excitation kinks in scalar parabolic equations.*<br>
   J Dyn Diff Equat. Published 30 July 2021; Volume 35, pages 2199-2235, (2023) [[DOI]](https://link.springer.com/article/10.1007/s10884-021-10040-2) [[arXiv]](https://arxiv.org/abs/2012.00309)
* M. Keßeböhmer, J.D.M. Rademacher, D. Ulbrich.<br>
  *Dynamics and topological entropy of 1D Greenberg-Hastings cellular automata.*<br>
   Ergodic Theory and Dynamical Systems. 2021;41(5):1397-1430 [[DOI]](https://www.cambridge.org/core/journals/ergodic-theory-and-dynamical-systems/article/dynamics-and-topological-entropy-of-1d-greenberghastings-cellular-automata/1DBE1EC4EC7BE9F216E9E35C214F2F3C) [[arXiv]](https://arxiv.org/abs/1903.02459)


### Theses

* D. Ulbrich.<br>
*Ergodic theory of nonlinear waves in discrete and continuous excitable media.*<br>
 Dissertation, 2021 [[DOI]](https://media.suub.uni-bremen.de/handle/elib/5257)

## Other

My Erd&#337;s number is 4 and the path is:  
D. Ulbrich -> M. Keßeböhmer -> M. Denker -> R. D. Mauldin -> P. Erd&#337;s 


<div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        Accordion Item #1
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <strong>This is the first item's accordion body.</strong> It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        Accordion Item #2
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <strong>This is the second item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingThree">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
        Accordion Item #3
      </button>
    </h2>
    <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <strong>This is the third item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
      </div>
    </div>
  </div>
</div>
